### ISSUE TITLE
Torch2

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/gaga-phsp#5]
There are 2 problems with torch2:
 - with Mac I have this error https://github.com/pytorch/pytorch/issues/78490
 - with Linux I have this error https://github.com/pytorch/pytorch/issues/91469

**Comment by milmor** [comment]
torch.compile is so great, but I can't harness it because it's impossible to train GANs. Tensorflow GAN with jit=True trainings are 2x faster than torch without compile. This is sad :( I love pytorch <3 Pytorch 2.0 training consumes 2x energy :( it's hard to afford that.

**Comment by tbaudier** [comment]
Finally we did not use compile function for our goals
